name: Deploy app

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - uses: robertkowalski/act-issue@main
        with:
          env: preview
